-- Import lua modules
require('core/keybindings')
require('core/options')
require('core/plugins')
require('lsp/lspconfig')
require('plugins/nvim-cmp')
require('plugins/nerdtree')
require('plugins/vim-airline')
require('plugins/comment')
require('colors')
