live_config_reload = true

[colors.cursor]
cursor = "#66fea0"
text = "#282C34"

[colors.normal]
black = "#282C34"
blue = "#61afef"
cyan = "#56B6C2"
green = "#66fea0"
magenta = "#C678DD"
red = "#E06C75"
white = "#DCDFE4"
yellow = "#E5C07B"

[colors.primary]
background = "#282C34"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "RobotoMono Nerd Font"

[font.offset]
x = 0
y = 3

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "Tab"
mods = "Control|Shift"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
